# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ShowWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ShowWindow(object):
    def setupUi(self, ShowWindow):
        ShowWindow.setObjectName("ShowWindow")
        ShowWindow.resize(700, 710)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/pngwing.com.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        ShowWindow.setWindowIcon(icon)
        ShowWindow.setStyleSheet("#centralwidget{\n"
"border-image: url(:/arkaplan/duvar-resimleri-kutuphane-kitap-raf-arka-plan-vektor.jpg.jpg);}")
        self.centralwidget = QtWidgets.QWidget(ShowWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.showMnRt = QtWidgets.QPushButton(self.centralwidget)
        self.showMnRt.setGeometry(QtCore.QRect(250, 540, 211, 71))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.showMnRt.setFont(font)
        self.showMnRt.setObjectName("showMnRt")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(80, 20, 550, 450))
        self.tableWidget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.tableWidget.setShowGrid(True)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 3, item)
        ShowWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(ShowWindow)
        self.statusbar.setObjectName("statusbar")
        ShowWindow.setStatusBar(self.statusbar)

        self.retranslateUi(ShowWindow)
        QtCore.QMetaObject.connectSlotsByName(ShowWindow)

    def retranslateUi(self, ShowWindow):
        _translate = QtCore.QCoreApplication.translate
        ShowWindow.setWindowTitle(_translate("ShowWindow", "ShowWindow"))
        self.showMnRt.setText(_translate("ShowWindow", "Return Main Page"))
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("ShowWindow", "Title"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("ShowWindow", "Author"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("ShowWindow", "Release"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("ShowWindow", "Page"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        self.tableWidget.setSortingEnabled(__sortingEnabled)
from icons import arkaplan_rc
from icons import icons_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ShowWindow = QtWidgets.QMainWindow()
    ui = Ui_ShowWindow()
    ui.setupUi(ShowWindow)
    ShowWindow.show()
    sys.exit(app.exec_())
